name: Update Notion with Steam Data

on:
  schedule:
    - cron: "5 22,06,14 * * *"
  workflow_dispatch:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: update notion games
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          # get from https://steamcommunity.com/dev/apikey
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          # get from your steam profile https://steamcommunity.com/profiles/{STEAM_USER_ID}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          # https://developers.notion.com/docs/create-a-notion-integration
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          # https://developers.notion.com/reference/retrieve-a-database
          include_played_free_games: ${{secrets.include_played_free_games}}
          #set to 'true' by default
          enable_item_update: ${{secrets.enable_item_update}}
          #set to 'true' by default
          enable_filter: ${{secrets.enable_filter}}
          #set to 'false' by default
        run: python main.py